------- Create tables ----------

-- Movement table
CREATE TABLE MOVEMENT
( ID_MOVEMENT VARCHAR2(150) NOT NULL,
  DATE_M DATE NOT NULL,
  DESCRIPTION VARCHAR2(256) NOT NULL,
  IMPORT_M FLOAT(2) NOT NULL,
  CATEGORY_M VARCHAR(4),
  CONSTRAINT MOVEMENT_PK PRIMARY KEY (ID_MOVEMENT) ENABLE);
  
-- Category table
CREATE TABLE CATEGORY
( ID_CATEGORY VARCHAR(4) NOT NULL,
  DESCRIPTION VARCHAR2(256) NOT NULL,
  REGULAR_EXP VARCHAR2(256),
  ID_CATEGORY_FATHER VARCHAR(4),
  CONSTRAINT CATEGORY_PK PRIMARY KEY (ID_CATEGORY) ENABLE);
  
-- Foreign key
ALTER TABLE MOVEMENT
ADD CONSTRAINT MOV_CATEGORY_FK FOREIGN KEY(CATEGORY_M)
                                REFERENCES CATEGORY(ID_CATEGORY) ENABLE;
  
ALTER TABLE CATEGORY
ADD CONSTRAINT CATEGORY_TYPE_FK FOREIGN KEY(ID_CATEGORY_FATHER)
                          REFERENCES CATEGORY(ID_CATEGORY) ENABLE;

commit;